### ISSUE TITLE
CSS Loader issue

### ISSUE THREAD

**Issue by webmastervishal** [okize/react-calendar-heatmap#102]
Hi there,
I am using the react-calender-heatmap in my react js project, the CSS loader has been added to web pack.

I tried to directly import the style sheet from the module but that didn't work.
So I copied the stylesheet from the link and imported it into the project but getting the same css loader issue.

Error: 

```
Error in ./../../../../static/css/react-calender-heatmap/styles.css
Module build failed: Syntax Error 

(5:1) Unknown word

  3 | // load the styles
  4 | var content = require("!!../../../node_modules/css-loader/index.js!./styles.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | // Prepare cssTransformation
  7 | var transform;
```
Not able to style the component kindly help.

**Comment by kevinsqi** [comment]
@webmastervishal sorry about the late reply. Not sure what the issue is - it's got to be some webpack CSS loader configuration issue, so it's outside the scope of this component, I think.

The demo codesandbox uses `import 'react-calendar-heatmap/dist/styles.css';
` through create-react-app without issue - you might want to take a look at it: https://codesandbox.io/s/73mk9wlyx

If you're still having trouble, please re-open this issue and include a runnable, reproducible example of your code (e.g. using codesandbox). Thanks!
